-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- vim.cmd([[colorscheme tokyonight-moon]])
-- vim.cmd([[colorscheme catppuccin-frappe]])
-- vim.cmd([[colorscheme abyss]])
-- vim.cmd([[colorscheme catppuccin-mocha]])
-- vim.cmd([[colorscheme kanagawa]])
-- vim.cmd([[colorscheme bluloco]])
-- vim.cmd([[colorscheme astrotheme-dark]])
vim.cmd([[colorscheme ayu-mirage]])
